SiteTitle: DbSyncKit
Logo: 
Host: DbSyncKit.dev
LinksUseHttps: true
MirrorResources: true
NetlifyRedirects: true
SourceFiles:
- ../../DbSyncKit.Core/**/{!.git,!bin,!obj,!packages,!*.Tests,!*.Templates,}/**/*.cs
- ../../DbSyncKit.DB/**/{!.git,!bin,!obj,!packages,!*.Tests,!*.Templates,}/**/*.cs
- ../../DbSyncKit.MSSQL/**/{!.git,!bin,!obj,!packages,!*.Tests,!*.Templates,}/**/*.cs
- ../../DbSyncKit.MySQL/**/{!.git,!bin,!obj,!packages,!*.Tests,!*.Templates,}/**/*.cs
- ../../DbSyncKit.Templates/**/{!.git,!bin,!obj,!packages,!*.Tests,}/**/*.cs
EditRoot: https://github.com/statiqdev/Website/edit/main/input
FontLink: "https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;700&family=Roboto+Slab:wght@400;700&family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Roboto+Thin:wght@200;700&display=swap"
ShouldOutput: true
sass-blue: "#48bdfe"
sass-indigo: "#bf4bff"
sass-purple: "#bf4bff"
sass-pink: "#ff5885"
sass-red: "#ff5885"
sass-orange: "#e98f00"
sass-yellow: "#e98f00"
sass-green: "#06c0af"
sass-teal: "#06c0af"
sass-cyan: "#06c0af"
sass-primary: "#0190df"
sass-secondary: "#9300e4"
sass-success: "#035d55"
sass-info: "#035d55"
sass-warning: "#835000"
sass-danger: "#f10041"
GenerateSearchIndex: true